app/App.tsx, components/Text.tsx
1. fix(App.tsx): handle error when creating state but mould not selected,
2. feat(Text.tsx): let user can update Text in workspace
=> 2 tasks in editor features

app/Explorer.tsx, app/MouldStates.tsx, app/types.ts, app/utils.ts, components/Kit.tsx, components/Stack/Inspector.tsx, components/Stack/RawStack.tsx, components/Stack/Stack.tsx, inspector/Blur.tsx, inspector/Border.tsx, inspector/Fill.tsx, inspector/Filters.tsx, inspector/FormComponents.tsx, inspector/Layout.tsx, inspector/Shadows.tsx
- tree-based mock adaptable property panel
- Stack's property panel
- fix some performance issues
=> complete Stack's property panel

app/MouldStates.tsx, app/View.tsx, app/Workspaces.tsx, app/appShell.ts, app/reducers.ts, app/types.ts
1. feat(*): rename state
2. feat(MouldStates): switch state in state list
=> editor features- state rename and switch

app/Kits/Item.tsx, app/appShell.ts
fix(Kits/Item): update attrs list ui and handle select duplicated
=> fix(Kits/Item): update dataMappingVector list ui in kit and handle select duplicated

.babelrc, app/App.tsx, app/Kits/Item.tsx, app/MouldMetas.tsx, components/CustomDragLayer.tsx, components/CustomDragLayer/GhostKitItem.tsx, inspector/FormComponents.tsx, next.config.js, package.json, tsconfig.json, yarn.lock
1. style(MouldMeta, FormComponents): use flexBasis to align inputs in MouldMeta
2. feat(*): Add CustomDragLayer and apply Kit Item
3. chore(*): add js module alias
=> Add CustomDragLayer and apply Kit Item

app/MouldMetas.tsx, app/Toolbar/PanelTrigger.tsx, app/Toolbar/index.tsx, app/appShell.ts, app/reducers.ts, app/style/App.scss, app/style/vars.scss, package.json
1.  add panel trigger
2. add trigger to hide other moulds
=> add panel trigger and add trigger to hide other moulds

app/Kits/Item.tsx, app/appShell.ts, app/reducers.ts
1. fix(appShell): the sort in hierarchy
2. feat(Kit/Item, *): add disconnectScopeToKit
=> fix drag error in hirerarchy and add close in kit-scope connection

app/MouldStates.tsx, app/Toolbar/AddMouldTrigger.tsx, app/Toolbar/Icons.tsx, app/Workspaces.tsx, app/appShell.ts, app/style/App.scss, app/types.ts, package.json, yarn.lock
1. fix(package.json, Workspace): zoom issue
2. fix(MouldStates): the editable state rename issue
3. feat(Toolbar/Icon, appShell, types): let user can click and drag a new state with atom component
4. fix(Workspace): update wheel region and smaller scale
5. feat(Toolbar/Icons, AddMouldTrigger): add active style in atom component
=> Few Interaction Fixes

app/App.tsx, app/Explorer.tsx, app/Inspectors.tsx, app/MouldMetas.tsx, app/MouldStates.tsx, app/Toolbar/AddMouldTrigger.tsx, app/Toolbar/Icons.tsx, app/Toolbar/index.tsx, app/style/App.scss, inspector/FormComponents.tsx, package.json, yarn.lock
1. fix(*): inspector in panel cannot scrolling by wheel
update dependency 'react-use-gesture' version
2. feat(*): modify mould name on state panel
3. fix(toolbar/*): the popover still display while dragging
=> Some Fixes in Editor

bin/mould, cli/index.js, package.json, yarn.lock
Add Mould Command-line interface
```sh
$ npm link
$ mould
Usage:
$ mould <command>
Available commands:
build, dev, init
Options:
--version, -v   output the version number
--help, -h      output usage information
```
=> feat(cli): add CLI

app/App.tsx, app/MouldScope.tsx, app/MouldStates.tsx, app/Toolbar/AddMouldTrigger.tsx, app/Toolbar/Icons.tsx, app/Toolbar/Resizer.tsx, app/Toolbar/index.tsx, app/Workspaces.tsx, app/appShell.ts, app/initialData.ts, app/reducers.ts, app/style/App.scss, app/style/Toolbar.scss, app/types.ts, lib/useClientRect.ts, package.json, yarn.lock
I has reviewed the WIP PR, which has lots of changes too. @bincer can merge that PR first, then I will pull and fix conflict in my local before this PR merged and reviewed in detail.
This changes are not very good at Atomic, if there are doubts, I will find a way to separate them
---
* Feat: Zoom in & Zoom out & Zoom 100
* Fix: the autofocus forbidden hot-key issue
* Fix: the view pinch and drag drop frame issue
* Fix: view performance
* Refactor: style canvas as relative and other to absolute to fix the height issue
* Refactor: substitute react-pinch-zoom
=> Update editor and refactor

app/App.tsx, app/MouldStates.tsx, app/appShell.ts, app/reducers.ts, app/utils.ts
* [main] - hit `ctrl + d` to duplicate view and auto select
* [sub]
* Fix the mould name style when too long
* Repair the mould card background
=> feat(*): duplicate view

app/utils.ts
* handled call too many hook error
=> fix(utils): break when delete view

cli/dev.js
Update CLI `dev` script to watch the `/mould` directory file changes
=> feat(cli): update dev script to watch mould directory

app/App.tsx, app/EditingMould.tsx, app/Explorer.tsx, app/Toolbar/AddMouldTrigger.tsx, app/Toolbar/Icons.tsx, app/Toolbar/Resizer.tsx, app/Toolbar/index.tsx, app/View.tsx, app/style/App.scss, controls/BooleanControl.tsx, controls/index.ts
* [main] - add bool control
* [sub]
* update tool bar style
* fix left panel scroll when too long
* handle error when moulds is an empty array
=> Add bool control and some fix

app/App.tsx, app/utils.ts
* [main] - fix the scope block disappear and archer mess
* [sub] - extract simulate scroll
=> fix(app, util): the scope block disappear and archer mess

cli/dev.ts, cli/index.js, cli/init.ts, package.json, yarn.lock
Update CLI scripts to support TS ESM so that `/compile/transform.ts` could be imported and invoked
=> feat(cli): run ts esm scripts

app/Workspaces.tsx, app/appShell.ts
* fix(workspace, appshell): useless tirgger when gesture execute
* fix(workspace): restrict the params when pinch zoom
=> fix(workspace, appshell): useless tirgger when gesture execute

cli/build.js, cli/compile.js, cli/constants.js, cli/dev.js, cli/init.js, cli/paths.js
Standardize and simplify CLI paths
=> feat(cli): simplify paths

cli/dev.js
When a user runs `mould dev`, we build Mould first, because another user could've changed something in the `/mould` directory
=> fix(cli): build Mould before running dev

app/View.tsx, app/Workspaces.tsx, lib/mouse-utils.ts, lib/useClientRect.ts
Improved user experience of using mouse to manipulate workspace
=> feat(workspace): improve user experience in workspace

components/Input/Input.tsx, components/Stack/Inspector.tsx, components/Stack/RawStack.tsx, components/Stack/Stack.tsx, components/Text/Text.tsx, standard/common.ts, standard/stack.ts
=> revert #120

components/Input/Input.tsx, components/Stack/Inspector.tsx, components/Stack/RawStack.tsx, components/Stack/Stack.tsx, components/Text/Text.tsx, standard/common.ts, standard/stack.ts
=> Revert "revert #120"

compile/transform.ts
Fix resolvers import for generated components
=> fix(compile): use default resolvers import

app/View.tsx
https://github.com/daybrush/moveable/issues/110
=> fix(View): input could not be focus if selected

app/types.ts, runtime/index.tsx
```
[stateName, scope] -> [scope, stateName]
```
=> fix(Runtime): adjust hooks return value

cli/dev.js
Add an extra check Mould Editor is installed before use
=> fix(cli): check Editor is installed before run

app/Tree.tsx, app/appShell.ts, app/reducers.ts
* add transform to Kit in tool item as an Anchor icon
* show the btn when it is pure node(not Kit)
* when transforming, it will add a kit in the mould and replace the original node.
---
=> feat(appshell, reducers, tree): transform to Kit

app/appShell.ts
Rudely skip the type check and run dev/build successfully.
=> fix(appshell): the type issue

app/Toolbar/Icons.tsx, app/Tree.tsx, app/types.ts, compile/transform.ts, components/Frame/ChildrenMoveable.tsx, components/Frame/Frame.tsx, components/Frame/Inspector.tsx, components/Frame/RawFrame.tsx, components/Frame/index.ts, components/Input/Input.tsx, components/Input/RawInput.tsx, components/Stack/ChildrenMoveable.tsx, components/Stack/Inspector.tsx, components/Stack/Stack.tsx, components/Stack/index.ts, components/Text/RawText.tsx, components/Text/Text.tsx, components/index.ts, inspector/InspectorProvider.tsx, inspector/Layout.tsx, mould.ts, runtime/index.tsx, standard/common.ts, standard/stack.ts
feat(component): add frame component
feat(stack component): add gap attributes
feat(inspector): add container related inspector
=> feat(component): add frame component & add container related inspector

app/App.tsx, app/Aside/Binding.tsx, app/Aside/LeftMenu.tsx, app/Aside/MappingTable.tsx, app/Aside/Operation.tsx, app/Aside/PropertySelectUtils.tsx, app/Aside/RightMenu.tsx, app/Aside/SuggestSelectUtils.tsx, app/MouldInput.tsx, app/MouldStates.tsx, app/Toolbar/DebugTrigger.tsx, app/Toolbar/InsertDialog/ComponentsList.tsx, app/Toolbar/InsertDialog/ComponentsListItem.tsx, app/Toolbar/InsertDialog/SearchBar.tsx, app/Toolbar/InsertDialog/index.tsx, app/Toolbar/PanelTrigger.tsx, app/Toolbar/index.tsx, app/View.tsx, app/appShell.ts, app/reducers.ts, app/style/App.scss, app/utils.ts, inspector/FormComponents.tsx
Features:
* Right Panel for 
* The Inputs in Binding Tab when isRoot
* Operation Tab simulate scroll
* Libraries list
* Decoupe Aside Panel as a individual component
* Move debug trigger to Header
* Suggest Select in mapping table
=> Update left/right panels UI

app/App.tsx
response data should be a `{ping: true}` as the apollo/resolvers
=> fix(App.tsx): the response field error
