mouldjs/mould

cli/init.js

Add `init` script for Mould CLI
```sh
$ mould init
Created mould directory at /Users/your_user/your_app
You could begin by typing:
mould dev
$ mould init
You already have mould initialized at /Users/your_user/your_app
You could begin by typing:
mould dev
```

feat(cli): add init script

---

cli/constants.js
cli/dev.js
cli/init.js

Add Mould Command-line interface
```sh
$ npm link
$ mould dev
You don't have mould initialized at /Users/your_user/your_app
You could start by typing:
mould init
$ mould init
Created mould directory at /Users/your_user/your_app
You could begin by typing:
mould dev
$ mould dev
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
[ info ]  bundled successfully, waiting for typecheck results...
[ ready ] compiled successfully - ready on http://localhost:3000
```

feat(cli): add dev script to run Mould

---

cli/constants.js
cli/dev.js
cli/init.js

Update `init` script to sumlink user's `/mould` directory to Mould's `/.mould` directory as per https://github.com/mouldjs/mould/pull/57
```sh
$ mould init
Created mould directory at /Users/your_user/your_app
Created resolvers.ts at /Users/your_user/your_app/mould
You could begin by typing:
mould dev
$ cd node_modules/mould && l
total 2152
drwxr-xr-x    35 your_user  staff   1.1K Jun 10 20:10 .
drwxr-xr-x  1222 your_user  staff    38K Jun 10 20:07 ..
...
lrwxr-xr-x     1 your_user  staff    49B Jun 10 20:10 .mould -> /Users/your_user/your_app/mould
...
```

feat(cli): update init script to symlink user's /mould to Mould's /.mould

---

app/Kits/Item.tsx
app/Kits/index.tsx
app/Tree.tsx
app/store.ts
components/Kit.tsx

- kit as Stack can accept children drag in
- kit as mould not displayed
- exclude unnecessary fields from undo/redo stacks

fix(editor): some bug fix & undo/redo improve

---

compile/transform.ts

Update `transform` paths to correctly import Mould components according to https://github.com/mouldjs/mould/pull/79
```js
import React from 'react'
import * as resolvers from '../.mould/resolvers'
import * as mould from '../mould'
```
Fix Mould components usage

feat(compile): update transform paths

---

app/Kits/Item.tsx
app/Kits/index.tsx
app/View.tsx

* [sub] feat(view): display mouldName in view title
* ref: https://stackoverflow.com/questions/53472795/uncaught-error-rendered-fewer-hooks-than-expected-this-may-be-caused-by-an-acc

fix(kit/item, index): the crash from switching view

---

cli/build.js
cli/compile.js
cli/constants.js
cli/copy.js
cli/dev.js
cli/init.js
cli/tsconfig.components.json
cli/tsconfig.mould.json
cli/utils.js
compile/transform.ts

Update `init` script to create either `resolvers.ts` or `resolvers.js` based on user environment 
Copy `resolvers.ts` into `/.components/resolvers.ts` and compile it into `/.components/resolvers.js` in order to import it in `/.components/index.js`
Copy `resolvers.js` into `/.components/resolvers.js` in order to import it in `/.components/index.js`

feat(cli): compile resolvers

---

package.json

Skip copying the `/release` directory into the `/release` directory

fix: skip copying release dir into release dir

---

compile/transform.ts

React component should return a valid React Element
```diff
export const Header = props => {
const [scopes, stateName] = resolvers['Header'](props)
switch(stateName) {
case "state0":
return <mould.components.Text  />
+       default:
+           return null
}
}
```
Without the `default` statement the function could return `undefined`, which breaks the React Component validation

fix(compile): update react component to return a valid react element

---

compile/transform.ts
mould.ts

Add types to `mould.ts` so that `tsc` could resolve them into `mould.d.ts` properly as follows
```ts
declare type ComponentsByType = {
[key: string]: AtomicComponent['Raw'];
};
declare type TransformsByType = {
[key: string]: AtomicComponent['Transform'];
};
export declare const components: ComponentsByType;
export declare const transforms: TransformsByType;
```
---
When we Compile Mould Schema into React components, `tsc` has a hard time checking the correctness of the components usage
```ts
import * as mould from '../mould'
export const Header = (props) => {
return <mould.components.Text />
}
```
because of the unclearness of the `components` variable 
```ts
// Before changes
export declare const components: {};
export declare const transforms: {};
```

feat: add types to root mould

---

cli/build.js
cli/compile.js
cli/copy.js
cli/dev.js

Migrate all the scripts to Promises, because we're updating our infrastructure so that we'll be able to run scripts in parallel, wait for their completion to run then sequentially

feat(cli): migrate to promises

---

cli/build.js
cli/dev.js
cli/init.js

Update CLI logs by adding `npx` so that users are able to use Mould CLI either from a terminal or by adding it to `package.json` `scripts`
`npx` executes a command form `node_modules/.bin` or from a central cache, so we need to install Mould before execution
```sh
create-react-app app
cd app
yarn add -D @mouldjs/mould
npx mould init
npx mould dev
```
```sh
create-react-app app
cd app
yarn add -D @mouldjs/mould
npx mould init
echo 'Edit package.json by adding "scripts": { "dev": "mould dev" }'
yarn dev
```

feat(cli): update log info by mentioning npx

---

package.json

If we don’t want to confuse Mould users, we need to make sure that all dependencies (both immediate and transitive) have compatible licenses with our package license.
Add `Apache-2.0` license, because dependency licenses should be more permissive or the same level of permissive as our package license:
`Apache-2.0` license:
* [`@blueprintjs/core`](https://github.com/palantir/blueprint/blob/develop/packages/core/package.json#L94)
* [`@blueprintjs/select`](https://github.com/palantir/blueprint/blob/develop/packages/select/package.json#L77)
* [`typescript`](https://github.com/microsoft/TypeScript/blob/master/package.json#L6)
`MIT` license:
* the rest dependencies

docs: add license

---

cli/build.js
cli/compile.js
cli/copy.js
cli/dev.js
cli/paths.js
cli/tsconfig.components.json
cli/utils.js

Compile the entire `.components` directory using `tsc`
We need to transpile our generated by Mould React Components, because they simply won't work when imported into another project, because Webpack is not configured to transpile the imported from `node_modules` code

feat(cli): compile the entire components directory using tsc

---

cli/init.js

Ensure Mould is initialized within an existing project root

fix(cli): ensure init is run within app directory

---

package.json
scripts/prepublish-checks.js

Update the `publish` process by extracting it from the `version` process
New flow looks as follows:
1. Since we can't push into `master` directly, we have to create a pull request with a new bumped version of the package.
```sh
npm version
git checkout -b && git commit && git push
hub pull-request
```
2. Once the pull request has been reviewed and merged, we'll be able to publish a new version of the package
```sh
git checkout master && git pull
yarn build
cd release
npm publish 
```
or using the `publish-package` script
```sh
git checkout master && git pull
yarn publish-package
```

fix(publish): separate version from publish

---

app/EditingMould.tsx
app/Tree.tsx
app/Workspaces.tsx
app/appShell.ts
app/reducers.ts
app/utils.ts
lib/undo-redux.ts

----
```
x: important operations (like create mould、modify mould tree ...)
-: unimportant operations (like move workspace、select mould ...)
x--------xxxx------
^1       ^2        ^3
```
> focus on Mould A -> modify this Mould -> move workspace n times -> focus on Mould B -> modify this Mould x times -> do some other unimportant things
1. _before_: undo to status 1, but still focus on other Mould, workspace moved to some place that can not see Mould A. So user may not aware of what was modified by undo operation. _after_: editor will perfectly back to status 1, user will always know what was changed when undo.
2. _before_: drag a slide to modify font size from 12 ~ 100. User may need undo (100 - 12 = 88) times. _after_: will merge changes happened in a short period of time.
3. _before_: …

Handle data size increase too large

---

app/store.ts

Just a simple change. But the problem i faced sometimes is that Apollo request return 500. Though this issue is still under observation, I guess it is because of the request body "schema" is too long. Since the #117, I haven't met it yet. So I think this is ok.

feat(store.ts, package.json, yarn.lock): format schema before saving

---

cli/dev.js
cli/paths.js

Update paths to use Mould Editor outside of `node_modules`

feat(cli): add editor path

---

cli/install.js

Add `install` script to install Mould Editor to the `~/.mould/{VERSION}` directory

feat(cli): add install script

---

cli/index.js
cli/uninstall.js

Add `uninstall` script to remove Mould Editor (`~/.mould`)

feat(cli): add uninstall script

---

inspector/InspectorProvider.tsx

Import `React` to fix build 
```jsx
inspector/InspectorProvider.tsx:60:13 - error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
60     return <Provider value={{ transform, renderer }}>{children}</Provider>
~~~~~~~~
Found 1 error.
```

fix(inspector): import React to use JSX

---

package.json

Use `--access public` to publish an Org scoped package as public

fix(publish): add access to publish-package script

---

components/List.tsx

Get rid of warning: `forwardRef` is used, but `ref` is not forwarded

fix(components): remove forwardRef because ref is not forwarded

---

app/CustomDragLayer/GhostKitItem.tsx
app/Kits/Item.tsx
app/MouldInput.tsx
app/MouldMetas.tsx
app/Toolbar/Icons.tsx
app/Toolbar/index.tsx
app/Tree.tsx
app/View.tsx
cli/build.js
cli/dev.js
cli/init.js
cli/paths.js
compile/transform.ts
components/Kit.tsx
components/Mould.tsx
components/index.ts
controls/index.ts
mould.ts
resources/Icons.js
runtime/index.tsx
scripts/ensure-test-workdir.js

add new entry: /mould/setup
```
// /mould/setup.ts
import CustomComponent from 'custom-lib'
export default ({Components, Controls}) => {
return {
Components: [...Components, {
type: 'custom component',
...CustomComponent
}],
Controls: CustomControls,
ViewWrapper:  View => () => <I18nProvider><NormalizeCSS><View /></NormalizeCSS></I18nProvider>
}
}
```
This setup function will run once the editor starts.

extendable editor

---

app/NodeToobar.tsx
app/Tree.tsx
app/appShell.ts

* decoupe the nodeToolbar from Tree
* fix the root node loss the functions
* repair the root use-case in wrapChild and TransformToKit
* Use independent condition because of the maintianable for future use.
* handle delete kit when root node is Kit

fix(appshell, nodetoolbar, tree): root node need the toolbar function

---

app/Toolbar/InsertDialog/SearchBar.tsx
app/Toolbar/InsertDialog/index.tsx

```
app/Toolbar/InsertDialog/SearchBar.tsx:27:9 - error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
27         <>
~~
app/Toolbar/InsertDialog/SearchBar.tsx:28:14 - error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
28             <Container>
~~~~~~~~~
app/Toolbar/InsertDialog/SearchBar.tsx:29:18 - error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
29                 <Search size="18" />
~~~~~~
app/Toolbar/InsertDialog/SearchBar.tsx:30:18 - error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
30                 <Input
~~~~~
Found 4 errors. …
```

fix: fix type issues

---

app/App.tsx
app/Entry.tsx

* simple tip popup when fetch no schema at first.
* ping query is only check the workspace id value if the server is alive.
* style is like below and the red error block is appeared when error again after clicked.

feat(*): add start mould tip popup
